### ISSUE TITLE
Ability to edit description

### ISSUE THREAD

**Issue by kroozo** [ulfschneider/breakdown#101]
Hi,
Would it be possible to edit the description of issues? It would be super useful.

I think it could be under the issue line, indented. I understand it is challenging because it is easy to mess up with the child items, but maybe simply having The lines under an issue not starting with Epic/Story/Task/Subtask be the description.

```
Story I want foobar
  This is a longer,
    
  multi line description...
  Sub-task create foo
  Sub-task create bar
``` 

Or maybe have an extra wrapper level like
```
Story I want foobar
  Description
    This is a longer,
    
    multi line description...
  Sub-task create foo
  Sub-task create bar
```

**Comment by ulfschneider** [comment]
It took some time – unfortunally – but it´s done now. v0.87.0 can handle descriptions when they are prefixed with a double slash //. Please refer to the [documentation](https://atom.io/packages/breakdown#creating-and-modifying-issues) for an example.
