### ISSUE TITLE
Fold description

### ISSUE THREAD

**Issue by holowinski** [ulfschneider/breakdown#104]
It would be nice to be able to fold/unfold descriptions.

Currently, when going through the tree if an issue has long description it makes it difficult to see what subtasks it has as those are shown below the description.

Ideally, descriptions show up folded by default and it's possible to unfold it when there's a need to edit.

**Comment by ulfschneider** [comment]
Konrad, are you aware that you can toggle the collapsing/expanding with CTRL-K-1, CTRL-K-2, ...?
CTRL-K-1 will show only the top level (epics), CTRL-K-2 will show Epics and Stories, but no Sub-tasks and descriptions. Isn´t that what you want?

**Comment by holowinski** [comment]
Yes, I'm aware of the shortcuts but this is not what I'm after.

In my case Epics / Stories might have long descriptions, and that means when I expand an Epic and Stories underneath to have an overview of all the stories and sub-tasks in that Epic descriptions take a lot of space and I can't clearly see the whole structure, I have to scroll up and down a lot to get the understanding of what's in the Epic.

i.e.

```
Epic PROJ-1 First Epic
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
   Story PROJ-2 First Story
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      Sub-task PROJ-6 Sub-task
   Story PROJ-3 Second Story
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
   Story PROJ-4 Third Story
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
   Story PROJ-5 Fourth Story
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
      //
...
```

In general, it seems there are two ways I'm using your plugin
1 - quick structure creation (Epics, Stories, Sub-tasks) - for this I don't really need descriptions - they obfuscate the view
2 - filling in details/reading details about tasks - here I need the decriptions.


It would be great to be able to fold/unfold description of a particular task, also it seems it would be great to be able to fold / unfold all descriptions in all tasks via `crtl-k-d` or something like that.

**Comment by ulfschneider** [comment]
The folding depends on indentation. With v0.90.0 the descriptions are indented in a way that allows folding the description.

**Comment by holowinski** [comment]
Thanks, checked it, works great.
