### ISSUE TITLE
Optionally skip time reporting

### ISSUE THREAD

**Issue by holowinski** [ulfschneider/breakdown#105]
With my current jira setup, whenever I try to create a sub-task it fails with an error caused by the originalEstimate not being able to be set for the task.

I've fixed / hacked it locally by doing 

```
      if (!issue.fields.timetracking) {
        return;
      }
```

in the `setOriginalEstimate` method in `breakdown-util.js`

It would be very cool to have a feature flag ? allowing to avoid this error - i.e. don't set originalEstimate for new tasks.

**Comment by ulfschneider** [comment]
I´m wondering if your adjustment could be a general rule?

**Comment by ulfschneider** [comment]
Ah no, it cannot be a general rule. Is the issue somehow dependent on the Sub-task setup of your Jira? Is it allowed to give an estimate for sub-tasks within your Jira UI?

**Comment by holowinski** [comment]
I can only create a sub-task from the User Story screen and doing so doesn't allow to provide any information beside the name.

I can add the details later on in the Sub-task details view, but it's impossible to do it when creating the Sub-task.

I'm using Jira Cloud.

**Comment by ulfschneider** [comment]
I´ve made an adjustment to not touch the timetracking in case 
1) there is no original estimate defined for the issue; and 
2) you are creating an issue.
Through that you should be able to work with sub-tasks in your environment when you avoid defining the original estimate for new sub-tasks.

**Comment by holowinski** [comment]
Thanks, just checked the new release and it works great.
Closing this one.
